[package]
name = "prac"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
notify-rust = "4.11.3"
num_cpus = "1.16.0"
tokio = {version = "1.41.0", features = ["full"]}